//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare020.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Healthcare020.Mobile.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://healthcare020-api.com:5001/api/.
        /// </summary>
        public static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://192.168.100.18:7500/api/.
        /// </summary>
        public static string ApiUrlAndroid {
            get {
                return ResourceManager.GetString("ApiUrlAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://healthcare020.cognitiveservices.azure.com/.
        /// </summary>
        public static string AzureFaceAPI_Endpoint {
            get {
                return ResourceManager.GetString("AzureFaceAPI_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e56df11bf5754139a03b2cc4170c2897.
        /// </summary>
        public static string AzureFaceAPI_Key {
            get {
                return ResourceManager.GetString("AzureFaceAPI_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena lozinke.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena lozinke.
        /// </summary>
        public static string ChangePasswordPageTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum pregleda.
        /// </summary>
        public static string DateOfPregled {
            get {
                return ResourceManager.GetString("DateOfPregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje može sadržati samo cifre.
        /// </summary>
        public static string DigitsOnlyError {
            get {
                return ResourceManager.GetString("DigitsOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor.
        /// </summary>
        public static string Doktor {
            get {
                return ResourceManager.GetString("Doktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena profila.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena profila.
        /// </summary>
        public static string EditProfilePageTitle {
            get {
                return ResourceManager.GetString("EditProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju.
        /// </summary>
        public static string ErrorWhenLoadingResourceMessage {
            get {
                return ResourceManager.GetString("ErrorWhenLoadingResourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare020_Pacijenti.
        /// </summary>
        public static string FaceAPI_PersonGroup {
            get {
                return ResourceManager.GetString("FaceAPI_PersonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to healthcare020_pacijenti_person_group_00423122.
        /// </summary>
        public static string FaceAPI_PersonGroupId {
            get {
                return ResourceManager.GetString("FaceAPI_PersonGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare020_Mobile.
        /// </summary>
        public static string IdpClientId {
            get {
                return ResourceManager.GetString("IdpClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devsecret_mobile.
        /// </summary>
        public static string IdpClientSecret {
            get {
                return ResourceManager.GetString("IdpClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://192.168.100.18:7600/connect/token.
        /// </summary>
        public static string IdpTokenEndpoint {
            get {
                return ResourceManager.GetString("IdpTokenEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://192.168.100.18:7600/connect/token.
        /// </summary>
        public static string IdpTokenEndpointAndroid {
            get {
                return ResourceManager.GetString("IdpTokenEndpointAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://192.168.100.18:7600/face-recognition.
        /// </summary>
        public static string IdpTokenEndpointFaceId {
            get {
                return ResourceManager.GetString("IdpTokenEndpointFaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje mora sadržati izmedju 2 i 20 slova.
        /// </summary>
        public static string ImePrezimeLengthError {
            get {
                return ResourceManager.GetString("ImePrezimeLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravno korisničko ime ili lozinka.
        /// </summary>
        public static string InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarska uverenja.
        /// </summary>
        public static string LekarskaUverenjaPageTitle {
            get {
                return ResourceManager.GetString("LekarskaUverenjaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje može sadržati samo slova.
        /// </summary>
        public static string LettersOnlyError {
            get {
                return ResourceManager.GetString("LettersOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logiranje...
        /// </summary>
        public static string LoggingInLoadingMessage {
            get {
                return ResourceManager.GetString("LoggingInLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalan broj karaketera je 180.
        /// </summary>
        public static string MaxLength180Error {
            get {
                return ResourceManager.GetString("MaxLength180Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napomena.
        /// </summary>
        public static string Napomena {
            get {
                return ResourceManager.GetString("Napomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka se mora razlikovati od stare.
        /// </summary>
        public static string NewPasswordSameAsOldValidationError {
            get {
                return ResourceManager.GetString("NewPasswordSameAsOldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi zahtev za pregled.
        /// </summary>
        public static string NoviZahtevZaPregledPageTitle {
            get {
                return ResourceManager.GetString("NoviZahtevZaPregledPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stara lozinka.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis stanja.
        /// </summary>
        public static string OpisStanja {
            get {
                return ResourceManager.GetString("OpisStanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda lozinke.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne podudaraju.
        /// </summary>
        public static string PasswordDoNotMatchError {
            get {
                return ResourceManager.GetString("PasswordDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržati izmedju 8 i 15 karaktera.
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string PreglediTabTitle {
            get {
                return ResourceManager.GetString("PreglediTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] prof {
            get {
                object obj = ResourceManager.GetObject("prof", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje.
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;  &lt;Modulus&gt;1nEbK/j2UssTOXcRdiroS2n1PoOlnfeY9S8dvSxFaD3oMpWkVjq32qt66by772WVHzpVX6aRASecCb91n1sk7LG9Jdqo6SMu47S61970nOYWOXdlyvuvXzR4l/bVSZrBRD72vjB2Yme+aggLZUzKgU1TsJ5SThOpCV/fSj6aD26C5w7chQdTUJNmqaGF4XnpvpU1ebE7mmKpU8aWdONEGsuAUHx50rh5bfNSHGcrR0pji1PQjBSoOskSGnVFTodDsYH3FeheDN9DjzjIrUBuZc8Asn4M8MCE6TKV1lN0voADTGYDBSSSwpIOQ4Hs0lsXFZzYyTcv1ugdTPMk8ZrcKdG8EmGXxlgyofq37hFMeiJgPOwDfyO6Pmq9po9RY3h6Yrob+AtGoxa4Jg0J4ecfRPrnurOlzzS9n2u4PIZLNWz/WLxJNVIUI+1o3UQvVecw8hf3EuMXUjFSNL6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RSAPublicKeyXml {
            get {
                return ResourceManager.GetString("RSAPublicKeyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga po doktoru.
        /// </summary>
        public static string SearchByDoktor {
            get {
                return ResourceManager.GetString("SearchByDoktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga po opisu stanja.
        /// </summary>
        public static string SearchByOpisStanja {
            get {
                return ResourceManager.GetString("SearchByOpisStanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga pregleda po napomeni.
        /// </summary>
        public static string SearchPreglediByNapomena {
            get {
                return ResourceManager.GetString("SearchPreglediByNapomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga zahteva za pregled po napomeni.
        /// </summary>
        public static string SearchZahteveZaPregledByNapomena {
            get {
                return ResourceManager.GetString("SearchZahteveZaPregledByNapomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 68a26225-ab2c-4034-94ba-227e043e7a8a.
        /// </summary>
        public static string ServiceIdentificationSecret {
            get {
                return ResourceManager.GetString("ServiceIdentificationSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string SettingsTabTitle {
            get {
                return ResourceManager.GetString("SettingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno kreiran korisnički nalog.
        /// </summary>
        public static string SuccessfullyCreatedAccount {
            get {
                return ResourceManager.GetString("SuccessfullyCreatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno kreiran zahtev za pregled.
        /// </summary>
        public static string SuccessfullyCreatedZahtevZaPregledMessage {
            get {
                return ResourceManager.GetString("SuccessfullyCreatedZahtevZaPregledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi pregledi.
        /// </summary>
        public static string Svi_preglediPageTitle {
            get {
                return ResourceManager.GetString("Svi preglediPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi pregledi.
        /// </summary>
        public static string SviPreglediPageTitle {
            get {
                return ResourceManager.GetString("SviPreglediPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknite za izmenu profilne slike.
        /// </summary>
        public static string TapToChangeProfilePicture {
            get {
                return ResourceManager.GetString("TapToChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju podataka.
        /// </summary>
        public static string UnableToLoadDataError {
            get {
                return ResourceManager.GetString("UnableToLoadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate biti autentificirani.
        /// </summary>
        public static string UnauthenticatedAccessMessage {
            get {
                return ResourceManager.GetString("UnauthenticatedAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neautorizovan pristup.
        /// </summary>
        public static string UnauthorizedAccessMessage {
            get {
                return ResourceManager.GetString("UnauthorizedAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspešna autentifikacija!.
        /// </summary>
        public static string UnsuccessfullyAuthentication {
            get {
                return ResourceManager.GetString("UnsuccessfullyAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora sadržati izmedju 4 i 12 karaktera.
        /// </summary>
        public static string UsernameLengthError {
            get {
                return ResourceManager.GetString("UsernameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno prosleđen zahtev za posetu.
        /// </summary>
        public static string UspesnoProsledjenZahtevZaPosetuMessage {
            get {
                return ResourceManager.GetString("UspesnoProsledjenZahtevZaPosetuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarska uverenja.
        /// </summary>
        public static string UverenjaTabTitle {
            get {
                return ResourceManager.GetString("UverenjaTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevi za pregled.
        /// </summary>
        public static string ZahteviTabTitle {
            get {
                return ResourceManager.GetString("ZahteviTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazani pregledi.
        /// </summary>
        public static string ZakazaniPreglediPageTitle {
            get {
                return ResourceManager.GetString("ZakazaniPreglediPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravstveno stanje.
        /// </summary>
        public static string ZdravstvenoStanje {
            get {
                return ResourceManager.GetString("ZdravstvenoStanje", resourceCulture);
            }
        }
    }
}
