//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare020.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Healthcare020.Mobile.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://healthcare020-api.com:5001/api/.
        /// </summary>
        public static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://10.0.2.2:5001/api/.
        /// </summary>
        public static string ApiUrlAndroid {
            get {
                return ResourceManager.GetString("ApiUrlAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena lozinke.
        /// </summary>
        public static string ChangePasswordPageTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje može sadržati samo cifre.
        /// </summary>
        public static string DigitsOnlyError {
            get {
                return ResourceManager.GetString("DigitsOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena profila.
        /// </summary>
        public static string EditProfilePageTitle {
            get {
                return ResourceManager.GetString("EditProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare020_Mobile.
        /// </summary>
        public static string IdpClientId {
            get {
                return ResourceManager.GetString("IdpClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devsecret_mobile.
        /// </summary>
        public static string IdpClientSecret {
            get {
                return ResourceManager.GetString("IdpClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://healthcare020-oauth.com:5005/connect/token.
        /// </summary>
        public static string IdpTokenEndpoint {
            get {
                return ResourceManager.GetString("IdpTokenEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://10.0.2.2:5005/connect/token.
        /// </summary>
        public static string IdpTokenEndpointAndroid {
            get {
                return ResourceManager.GetString("IdpTokenEndpointAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje mora sadržati izmedju 2 i 20 slova.
        /// </summary>
        public static string ImePrezimeLengthError {
            get {
                return ResourceManager.GetString("ImePrezimeLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravno korisničko ime ili lozinka.
        /// </summary>
        public static string InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarska uverenja.
        /// </summary>
        public static string LekarskaUverenjaPageTitle {
            get {
                return ResourceManager.GetString("LekarskaUverenjaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje može sadržati samo slova.
        /// </summary>
        public static string LettersOnlyError {
            get {
                return ResourceManager.GetString("LettersOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logiranje...
        /// </summary>
        public static string LoggingInLoadingMessage {
            get {
                return ResourceManager.GetString("LoggingInLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne podudaraju.
        /// </summary>
        public static string PasswordDoNotMatchError {
            get {
                return ResourceManager.GetString("PasswordDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržati izmedju 8 i 15 karaktera.
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string PreglediTabTitle {
            get {
                return ResourceManager.GetString("PreglediTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] prof {
            get {
                object obj = ResourceManager.GetObject("prof", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje.
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string SettingsTabTitle {
            get {
                return ResourceManager.GetString("SettingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno kreiran korisnički nalog.
        /// </summary>
        public static string SuccessfullyCreatedAccount {
            get {
                return ResourceManager.GetString("SuccessfullyCreatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora sadržati izmedju 4 i 12 karaktera.
        /// </summary>
        public static string UsernameLengthError {
            get {
                return ResourceManager.GetString("UsernameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekarska uverenja.
        /// </summary>
        public static string UverenjaTabTitle {
            get {
                return ResourceManager.GetString("UverenjaTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevi za pregled.
        /// </summary>
        public static string ZahteviTabTitle {
            get {
                return ResourceManager.GetString("ZahteviTabTitle", resourceCulture);
            }
        }
    }
}
