//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare020.Services.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecurityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthCare020.Services.Security.SecurityResources", typeof(SecurityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;  &lt;D&gt;Q0zMEkjYRbOmHOrZeBSPQtvGNBBs8d67Cnf3BV/XiJelP/rm0IktGlum/6RT9xYSbvKHyLUl3Q7pUcXczF52gDJoAnFVgZWhKaWW3hkC/BrZ7r8iG0pSB7cYAdldpvQCo8B+/8GF5exZPj24Fdq700jJcyy89/QDoQWNtmdfQmiUfJ+VZcqewzL/jU08Dz+LtFxvo/mTkyhTrA8vOQ/6V852PsxSD2gF9BPhOTjHxF/8TcXINa5l/c0M+XDEh5i8DgGT4jRDEBchxNk1YepOu3Tz6xDUTtqc2/McQ199zCuw3VFGsV6BEL916onkIUClRgsrnjrLsM64I2ZLuee4IHRAsI1WmgLHOD3n7hqZqKw9bzDEIYLhXVeUl4Xp3PY9y3deFxdHlYaPgG4Lrxq88qpRiss9foKGd8UGG7Ypy/r+OCBHDY3e1SBFijm3JaEiYpI5hbVhsEQ9s8F2G6oPsahIWuiCQqqP3kWCed78oCVALf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSAPrivateKey {
            get {
                return ResourceManager.GetString("RSAPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 68a26225-ab2c-4034-94ba-227e043e7a8a.
        /// </summary>
        internal static string ServiceIdentificationSecret {
            get {
                return ResourceManager.GetString("ServiceIdentificationSecret", resourceCulture);
            }
        }
    }
}
