//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare020.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Healthcare020.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate potrebne permisije.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne podudaraju.
        /// </summary>
        public static string DifferentPasswords {
            get {
                return ResourceManager.GetString("DifferentPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi pregledi.
        /// </summary>
        public static string frmDoktorPregledi {
            get {
                return ResourceManager.GetString("frmDoktorPregledi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevi za pregled.
        /// </summary>
        public static string frmDoktorZahteviZaPreglede {
            get {
                return ResourceManager.GetString("frmDoktorZahteviZaPreglede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazani pregledi.
        /// </summary>
        public static string frmDoktorZakazaniPregledi {
            get {
                return ResourceManager.GetString("frmDoktorZakazaniPregledi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Države.
        /// </summary>
        public static string frmDrzave {
            get {
                return ResourceManager.GetString("frmDrzave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Gradovi.
        /// </summary>
        public static string frmGradovi {
            get {
                return ResourceManager.GetString("frmGradovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Naucne oblasti.
        /// </summary>
        public static string frmNaucneOblasti {
            get {
                return ResourceManager.GetString("frmNaucneOblasti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Nova država.
        /// </summary>
        public static string frmNewDrzavaAdd {
            get {
                return ResourceManager.GetString("frmNewDrzavaAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Izmena države.
        /// </summary>
        public static string frmNewDrzavaUpdate {
            get {
                return ResourceManager.GetString("frmNewDrzavaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Novi grad.
        /// </summary>
        public static string frmNewGradAdd {
            get {
                return ResourceManager.GetString("frmNewGradAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Izmena grada.
        /// </summary>
        public static string frmNewGradUpdate {
            get {
                return ResourceManager.GetString("frmNewGradUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Nova naučna oblast.
        /// </summary>
        public static string frmNewNaucnaOblastAdd {
            get {
                return ResourceManager.GetString("frmNewNaucnaOblastAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Izmena naučne oblasti.
        /// </summary>
        public static string frmNewNaucnaOblastUpdate {
            get {
                return ResourceManager.GetString("frmNewNaucnaOblastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Nova uloga.
        /// </summary>
        public static string frmNewRoleAdd {
            get {
                return ResourceManager.GetString("frmNewRoleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Izmena uloge.
        /// </summary>
        public static string frmNewRoleUpdate {
            get {
                return ResourceManager.GetString("frmNewRoleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi korisnički nalog.
        /// </summary>
        public static string frmNewUser {
            get {
                return ResourceManager.GetString("frmNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Novo zdavstveno stanje.
        /// </summary>
        public static string frmNewZdravstvenoStanjeAdd {
            get {
                return ResourceManager.GetString("frmNewZdravstvenoStanjeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Izmena zdravstvenog stanja.
        /// </summary>
        public static string frmNewZdravstvenoStanjeUpdate {
            get {
                return ResourceManager.GetString("frmNewZdravstvenoStanjeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika - Posete.
        /// </summary>
        public static string frmPoseteStatistic {
            get {
                return ResourceManager.GetString("frmPoseteStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci.
        /// </summary>
        public static string frmPredefinedData {
            get {
                return ResourceManager.GetString("frmPredefinedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika - Obavljeni pregledi.
        /// </summary>
        public static string frmPreglediStatistic {
            get {
                return ResourceManager.GetString("frmPreglediStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Uloge.
        /// </summary>
        public static string frmRoles {
            get {
                return ResourceManager.GetString("frmRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratorski meni.
        /// </summary>
        public static string frmStartMenuAdmin {
            get {
                return ResourceManager.GetString("frmStartMenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika.
        /// </summary>
        public static string frmStatisticsMenu {
            get {
                return ResourceManager.GetString("frmStatisticsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički nalozi.
        /// </summary>
        public static string frmUsers {
            get {
                return ResourceManager.GetString("frmUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika - Zahtevi za pregled.
        /// </summary>
        public static string frmZahteviZaPregledStatistic {
            get {
                return ResourceManager.GetString("frmZahteviZaPregledStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisani podaci - Zdravstvena stanja.
        /// </summary>
        public static string frmZdravstvenaStanja {
            get {
                return ResourceManager.GetString("frmZdravstvenaStanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ženski.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muški.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Healthcare020_Icon {
            get {
                object obj = ResourceManager.GetObject("Healthcare020_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Healthcare020_Logo_210x210 {
            get {
                object obj = ResourceManager.GetObject("Healthcare020_Logo_210x210", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Healthcare020_Logo_250x250 {
            get {
                object obj = ResourceManager.GetObject("Healthcare020_Logo_250x250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Healthcare020_Logo_500x500 {
            get {
                object obj = ResourceManager.GetObject("Healthcare020_Logo_500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klinički centar UCS.
        /// </summary>
        public static string InstitutionName {
            get {
                return ResourceManager.GetString("InstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke moraju biti iste.
        /// </summary>
        public static string InvalidPasswordConfirmation {
            get {
                return ResourceManager.GetString("InvalidPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drzava.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kreiranja.
        /// </summary>
        public static string LabelDateCreated {
            get {
                return ResourceManager.GetString("LabelDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmailAddress {
            get {
                return ResourceManager.GetString("LabelEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        public static string LabelGender {
            get {
                return ResourceManager.GetString("LabelGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG.
        /// </summary>
        public static string LabelJmbg {
            get {
                return ResourceManager.GetString("LabelJmbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lični podaci.
        /// </summary>
        public static string LabelPersonalData {
            get {
                return ResourceManager.GetString("LabelPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string LabelPhoneNumber {
            get {
                return ResourceManager.GetString("LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        public static string LabelRole {
            get {
                return ResourceManager.GetString("LabelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigurnost.
        /// </summary>
        public static string LabelSecurity {
            get {
                return ResourceManager.GetString("LabelSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički profil.
        /// </summary>
        public static string LabelUserProfile {
            get {
                return ResourceManager.GetString("LabelUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno nema dostupnih poseta.
        /// </summary>
        public static string NoDataPosete {
            get {
                return ResourceManager.GetString("NoDataPosete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno nema dostupnih poseta.
        /// </summary>
        public static string NoDataPoseteStatisticMessage {
            get {
                return ResourceManager.GetString("NoDataPoseteStatisticMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno nema dostupnih obavljenih pregleda.
        /// </summary>
        public static string NoDataPreglediObavljeniStatisticMessage {
            get {
                return ResourceManager.GetString("NoDataPreglediObavljeniStatisticMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno nema dostpunih zahteva za pregled.
        /// </summary>
        public static string NoDataZahteviZaPregledStatisticMessage {
            get {
                return ResourceManager.GetString("NoDataZahteviZaPregledStatisticMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Niste prijavljeni na sistem!&quot;.
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj obavljenih pregleda.
        /// </summary>
        public static string StatisticCountYAxisTitle {
            get {
                return ResourceManager.GetString("StatisticCountYAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz broja poseta po mesecima.
        /// </summary>
        public static string TitlePoseteStatistic {
            get {
                return ResourceManager.GetString("TitlePoseteStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz broja obavljenih pregleda po mesecima.
        /// </summary>
        public static string TitlePreglediStatistic {
            get {
                return ResourceManager.GetString("TitlePreglediStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz broja zahteva za preglede po mesecima.
        /// </summary>
        public static string TitleZahteviZaPregledeStatistic {
            get {
                return ResourceManager.GetString("TitleZahteviZaPregledeStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće učitati lične podatke.
        /// </summary>
        public static string UnableToLoadPersonalData {
            get {
                return ResourceManager.GetString("UnableToLoadPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće učitati podatke o profilu.
        /// </summary>
        public static string UnableToLoadUserProfileMessage {
            get {
                return ResourceManager.GetString("UnableToLoadUserProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netačno korisničko ime ili lozinka.
        /// </summary>
        public static string WrongUsernameOrPasswordMessage {
            get {
                return ResourceManager.GetString("WrongUsernameOrPasswordMessage", resourceCulture);
            }
        }
    }
}
